// <auto-generated />
using Menu.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Menu.Migrations
{
    [DbContext(typeof(FoodFoolioContext))]
    [Migration("20240505191441_Initial Data-Migration")]
    partial class InitialDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Menu.Models.Dishes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A classic pizza with a simple yet flavorful combination of tomato sauce, mozzarella cheese, and fresh basil leaves.",
                            IconUrl = "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSxsG9qQnPbVfptj92kjVpfdbpL4D8suUcIN0aFP7FGRJDLUKxtdVwKTV2ItvzO",
                            Title = "Margherita",
                            price = 7.5
                        },
                        new
                        {
                            Id = 2,
                            Description = "A savory pizza topped with tomato sauce, mozzarella cheese, and slices of pepperoni.",
                            IconUrl = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQM7Huw9KIbgfKhUvsiYQM2rIgEiutB9C1av6QdWIN1cOylbKZBG4fO9vtrZ4yg",
                            Title = "Pepperoni",
                            price = 8.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "A sweet and savory pizza with a combination of tomato sauce, mozzarella cheese, ham, and pineapple chunks.",
                            IconUrl = "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQMr1lt-dtorMSZZ-nRdt1pXYTiIFyw67wLEPyJduDdChZFpoO2xjXHEVDemAJ1",
                            Title = "Hawaiian",
                            price = 8.5
                        },
                        new
                        {
                            Id = 4,
                            Description = ".A hearty pasta dish with spaghetti noodles tossed in a rich meat sauce made with ground beef, tomatoes, and herbs.",
                            IconUrl = "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQcSWMzXC-JRbwX3_tFph1GKKiVZHR3rVZgLUWcRVO7C_mIziPJgVAB0KJW4GfT",
                            Title = "Spaghetti Bolognese",
                            price = 9.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "A layered pasta dish with lasagna noodles, ricotta cheese, mozzarella cheese, tomato sauce, and ground meat.",
                            IconUrl = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR5RXtq-tqkSkPiWN7tWoJKSrHp-2aa7HQVX8rPz4O0w_TM5dByVQwEEmPxjxF5",
                            Title = "Lasagna",
                            price = 10.0
                        },
                        new
                        {
                            Id = 6,
                            Description = "A creamy pasta dish with penne noodles tossed in a Parmesan cheese sauce with butter and black pepper.",
                            IconUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYTLZLqzRg7MzSiOxfXgHfc2kbQxXjciNHSN2T3UQY1P3cpXCFYVdg_1vE06IP",
                            Title = "Penne Alfredo",
                            price = 8.5
                        },
                        new
                        {
                            Id = 7,
                            Description = "A refreshing salad with romaine lettuce, croutons, Parmesan cheese, and a creamy Caesar dressing.",
                            IconUrl = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRY_eHLujovQQKHoeGQ2ho_R73kjUG-tcme2kuFnrYYFsgPenARAOmeRHv4EtNN",
                            Title = "Caesar Salad",
                            price = 7.0
                        },
                        new
                        {
                            Id = 8,
                            Description = "A flavorful salad with tomatoes, cucumbers, olives, feta cheese, red onions, and a vinaigrette dressing.",
                            IconUrl = "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS7BGGe7zXLXiMk3iGCL3y_KYmn_R8ix7eUmMKciJLtFYXks3sQrqlQeCacNRmh",
                            Title = "Greek Salad",
                            price = 8.0
                        },
                        new
                        {
                            Id = 9,
                            Description = "A simple yet elegant salad with sliced tomatoes, fresh mozzarella cheese, basil leaves, and a drizzle of olive oil.",
                            IconUrl = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRqzkSO9s8p9QHaVspPV5DjYxJokiiCPeQBRm8tdPLKI_oR11VUU-sxLQg3wUcb",
                            Title = "Caprese Salad",
                            price = 6.5
                        },
                        new
                        {
                            Id = 10,
                            Description = "A healthy and flavorful dish of grilled chicken breast, seasoned and cooked to perfection.",
                            IconUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgN-KUvxE4w71iUPs972XH_7Xx_x_6YuavBDsEo9aBlCNCVCj-4i6K2Rbr3ZHb",
                            Title = "Grilled Chicken",
                            price = 12.0
                        },
                        new
                        {
                            Id = 11,
                            Description = "A nutritious dish featuring roasted salmon served with a variety of roasted vegetables.",
                            IconUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg7Lk_L0otNgiJvXq7DBc7eie38_8HENKA8mJcZKRwPJcD4hKsiL4EfgXWL0JF",
                            Title = "Salmon with Roasted Vegetables",
                            price = 14.0
                        },
                        new
                        {
                            Id = 12,
                            Description = "A comforting and hearty stew made with beef, vegetables, and a rich broth.",
                            IconUrl = "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTQ48Ukd0OSZLbGDGuBe4p3ds32NZvRhYDKxgfBMzvglgO2OnnA9aF5xbM9Pj8J",
                            Title = "Beef Stew",
                            price = 13.5
                        },
                        new
                        {
                            Id = 13,
                            Description = "A decadent chocolate cake, perfect for satisfying your sweet tooth.",
                            IconUrl = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTEiGGqQ2hhECMjGf7l53cQd08LaXaBhzyVVzToUY6tGmnyz6V2FFok-qmPN25g",
                            Title = "Chocolate Cake",
                            price = 5.0
                        },
                        new
                        {
                            Id = 14,
                            Description = "A creamy and delicious cheesecake, a classic dessert favorite.",
                            IconUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvcp9lQnaRjUfNivxdDDCctlee0fb7euLGUMpnnEzGkIvuaWeZ8tGHMuwrkBxp",
                            Title = "Cheesecake",
                            price = 5.5
                        },
                        new
                        {
                            Id = 15,
                            Description = "An Italian coffee-flavored dessert made with ladyfingers, mascarpone cheese, cocoa powder, and coffee.",
                            IconUrl = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR03GLSb-AGl6J-BRf37jAzisO6CPUCJohEMSv4lxmkQ2FXHRohhX2iohc6UFNu",
                            Title = "Tiramisu",
                            price = 6.0
                        });
                });

            modelBuilder.Entity("Menu.Models.Dishngredients", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("Dishngredients");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 5
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 10
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 11
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 11
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 10
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 20
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 11
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 11
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 19
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 14
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 10
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 9,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 9,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 9,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 9,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 10,
                            IngredientId = 12
                        },
                        new
                        {
                            DishId = 10,
                            IngredientId = 14
                        },
                        new
                        {
                            DishId = 10,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 11,
                            IngredientId = 13
                        },
                        new
                        {
                            DishId = 11,
                            IngredientId = 14
                        },
                        new
                        {
                            DishId = 11,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 15
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 16
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 17
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 18
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 10
                        },
                        new
                        {
                            DishId = 12,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 13,
                            IngredientId = 19
                        },
                        new
                        {
                            DishId = 13,
                            IngredientId = 20
                        },
                        new
                        {
                            DishId = 13,
                            IngredientId = 21
                        },
                        new
                        {
                            DishId = 14,
                            IngredientId = 19
                        },
                        new
                        {
                            DishId = 14,
                            IngredientId = 20
                        },
                        new
                        {
                            DishId = 14,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 15,
                            IngredientId = 19
                        },
                        new
                        {
                            DishId = 15,
                            IngredientId = 23
                        },
                        new
                        {
                            DishId = 15,
                            IngredientId = 22
                        },
                        new
                        {
                            DishId = 15,
                            IngredientId = 24
                        },
                        new
                        {
                            DishId = 15,
                            IngredientId = 20
                        },
                        new
                        {
                            DishId = 15,
                            IngredientId = 21
                        });
                });

            modelBuilder.Entity("Menu.Models.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "tomato sauce"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mozzarella cheese"
                        },
                        new
                        {
                            Id = 3,
                            Name = "pepperoni"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ham"
                        },
                        new
                        {
                            Id = 5,
                            Name = "pineapple"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ground beef"
                        },
                        new
                        {
                            Id = 7,
                            Name = "pasta"
                        },
                        new
                        {
                            Id = 8,
                            Name = "basil"
                        },
                        new
                        {
                            Id = 9,
                            Name = "olive oil"
                        },
                        new
                        {
                            Id = 10,
                            Name = "garlic"
                        },
                        new
                        {
                            Id = 11,
                            Name = "parmesan cheese"
                        },
                        new
                        {
                            Id = 12,
                            Name = "chicken breast"
                        },
                        new
                        {
                            Id = 13,
                            Name = "salmon fillet"
                        },
                        new
                        {
                            Id = 14,
                            Name = "vegetables (mixed)"
                        },
                        new
                        {
                            Id = 15,
                            Name = "beef"
                        },
                        new
                        {
                            Id = 16,
                            Name = "potatoes"
                        },
                        new
                        {
                            Id = 17,
                            Name = "carrots"
                        },
                        new
                        {
                            Id = 18,
                            Name = "celery"
                        },
                        new
                        {
                            Id = 19,
                            Name = "eggs"
                        },
                        new
                        {
                            Id = 20,
                            Name = "cream cheese"
                        },
                        new
                        {
                            Id = 21,
                            Name = "cocoa powder"
                        },
                        new
                        {
                            Id = 22,
                            Name = "ladyfingers"
                        },
                        new
                        {
                            Id = 23,
                            Name = "mascarpone cheese"
                        },
                        new
                        {
                            Id = 24,
                            Name = "coffee"
                        });
                });

            modelBuilder.Entity("Menu.Models.Dishngredients", b =>
                {
                    b.HasOne("Menu.Models.Dishes", "dishes")
                        .WithMany("dishngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menu.Models.Ingredients", "Ingredients")
                        .WithMany("Dishngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredients");

                    b.Navigation("dishes");
                });

            modelBuilder.Entity("Menu.Models.Dishes", b =>
                {
                    b.Navigation("dishngredients");
                });

            modelBuilder.Entity("Menu.Models.Ingredients", b =>
                {
                    b.Navigation("Dishngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
